import { 
  Merge, 
  Scissors, 
  Minimize2, 
  RotateCcw, 
  Image as ImageIcon, 
  FileText, 
  FileImage, 
  Type, 
  Trash2, 
  Plus, 
  Download, 
  Sparkles, 
  Languages, 
  FileSearch,
  FileSpreadsheet,
  Hash,
  Stamp,
  Edit,
  Lock,
  Camera,
  Presentation,
  Wrench,
  Hammer,
  MessageSquare,
  FileDigit,
  FileSignature,
  FileCheck,
  FileUp,
  FileDown,
  FileCode,
  Files
} from "lucide-react";

export const TOOLS = [
  {
    id: "scan-to-pdf",
    name: "Scan to PDF",
    description: "Capture photos from your camera and convert them directly to PDF.",
    icon: Camera,
    category: "pdf",
    color: "bg-gradient-to-br from-emerald-400 to-emerald-600",
  },
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDFs into one document easily.",
    icon: Files,
    category: "pdf",
    color: "bg-gradient-to-br from-red-500 to-rose-700",
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce the file size of your PDF while optimizing for maximal quality.",
    icon: Minimize2,
    category: "pdf",
    color: "bg-gradient-to-br from-amber-400 to-orange-600",
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG images to PDF in seconds. Easily adjust orientation and margins.",
    icon: FileImage,
    category: "pdf",
    color: "bg-gradient-to-br from-indigo-500 to-blue-700",
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert your PDF documents to editable Word files.",
    icon: FileText,
    category: "pdf",
    color: "bg-gradient-to-br from-blue-500 to-blue-700",
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert your Word documents to high-quality PDF files.",
    icon: FileUp,
    category: "pdf",
    color: "bg-gradient-to-br from-blue-600 to-indigo-800",
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert Excel spreadsheets to high-quality PDF files.",
    icon: FileSpreadsheet,
    category: "pdf",
    color: "bg-gradient-to-br from-green-500 to-emerald-700",
  },
  {
    id: "watermark-pdf",
    name: "Watermark PDF",
    description: "Add text watermarks to your PDF documents.",
    icon: Stamp,
    category: "pdf",
    color: "bg-gradient-to-br from-sky-400 to-blue-600",
  },
  {
    id: "remove-pages",
    name: "Remove Pages",
    description: "Delete unwanted pages from your PDF document.",
    icon: Trash2,
    category: "pdf",
    color: "bg-gradient-to-br from-red-600 to-red-800",
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    description: "Extract pages from your PDF or save each page as a separate PDF.",
    icon: Scissors,
    category: "pdf",
    color: "bg-gradient-to-br from-orange-400 to-orange-600",
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate your PDF pages and save them permanently.",
    icon: RotateCcw,
    category: "pdf",
    color: "bg-gradient-to-br from-lime-500 to-green-700",
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Extract all images from a PDF or convert each page to a JPG image.",
    icon: ImageIcon,
    category: "pdf",
    color: "bg-gradient-to-br from-violet-500 to-purple-700",
  },
  {
    id: "page-numbers-pdf",
    name: "Page Numbers",
    description: "Add page numbers to your PDF document automatically.",
    icon: Hash,
    category: "pdf",
    color: "bg-gradient-to-br from-zinc-500 to-zinc-700",
  },
  {
    id: "edit-pdf",
    name: "Edit PDF",
    description: "Add text annotations and edit your PDF document.",
    icon: Edit,
    category: "pdf",
    color: "bg-gradient-to-br from-indigo-600 to-violet-800",
  },
  {
    id: "lock-pdf",
    name: "Lock PDF",
    description: "Protect your PDF document with a password.",
    icon: Lock,
    category: "pdf",
    color: "bg-gradient-to-br from-slate-600 to-slate-800",
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password protection from your PDF document.",
    icon: Wrench,
    category: "pdf",
    color: "bg-gradient-to-br from-zinc-400 to-zinc-600",
  },
  {
    id: "summarize-pdf",
    name: "Summarize PDF",
    description: "Automatically summarize long PDF documents and extract key points.",
    icon: Sparkles,
    category: "pdf",
    color: "bg-gradient-to-br from-cyan-400 to-blue-600",
    features: ["Concise Bullet Points", "Key Insights Extraction", "Multi-page Support", "Fast Processing"],
    proTip: "For best results, select only the most relevant pages to summarize."
  },
  {
    id: "ocr-pdf",
    name: "Extract Text (OCR)",
    description: "Extract text from scanned PDFs and images using advanced recognition.",
    icon: FileSearch,
    category: "pdf",
    color: "bg-gradient-to-br from-teal-400 to-emerald-600",
    features: ["Optical Character Recognition", "Handwriting Support", "Table Data Extraction", "Multi-language Support"],
    proTip: "Ensure the document is well-lit and flat for the most accurate text extraction."
  },
  {
    id: "compress-image",
    name: "Compress Image",
    description: "Reduce the file size of your images without losing quality.",
    icon: Minimize2,
    category: "image",
    color: "bg-gradient-to-br from-purple-400 to-fuchsia-600",
  },
  {
    id: "convert-image",
    name: "Convert Image",
    description: "Convert your images to JPG, PNG, or WEBP formats.",
    icon: ImageIcon,
    category: "image",
    color: "bg-gradient-to-br from-pink-400 to-rose-600",
  },
  {
    id: "add-pages",
    name: "Add Pages",
    description: "Insert new pages into your existing PDF document.",
    icon: Plus,
    category: "pdf",
    color: "bg-gradient-to-br from-green-600 to-green-800",
  },
  {
    id: "pptx-to-pdf",
    name: "PowerPoint to PDF",
    description: "Convert your PowerPoint presentations to high-quality PDF files.",
    icon: Presentation,
    category: "pdf",
    color: "bg-gradient-to-br from-orange-600 to-red-700",
  },
  {
    id: "repair-pdf",
    name: "Repair PDF",
    description: "Fix corrupted or damaged PDF documents and recover their content.",
    icon: Hammer,
    category: "pdf",
    color: "bg-gradient-to-br from-zinc-700 to-zinc-900",
  },
  {
    id: "chat-pdf",
    name: "Chat with PDF",
    description: "Interact with your PDF documents to ask questions and get insights.",
    icon: MessageSquare,
    category: "pdf",
    color: "bg-gradient-to-br from-purple-600 to-indigo-800",
    features: ["Interactive Q&A", "Context-aware Responses", "Document Analysis", "Instant Insights"],
    proTip: "You can ask specific questions like 'What is the total amount in the invoice?' or 'Summarize the conclusion section'."
  },
  {
    id: "esign-pdf",
    name: "E-Sign PDF",
    description: "Draw, type, or upload your signature and place it anywhere on your PDF documents.",
    icon: FileSignature,
    category: "pdf",
    color: "bg-gradient-to-br from-violet-500 to-indigo-700",
    features: ["Interactive Drag & Drop", "Stylish Signature Fonts", "Date & Verified Badge Stamps", "Secure Processing"],
    proTip: "You can place multiple signatures across different pages and resize them visually before applying."
  }
];

